### ISSUE TITLE
500 Error when trying to index a package 

### ISSUE THREAD

**Issue by pombredanne** [nexB/purldb#193]
https://localhost/api/packages/get_or_fetch_package/?purl=pkg:maven/commons-daemon/commons-daemon@1.3.4 returns 
Server Error (500)

The package does not have anything special I can see: https://repo1.maven.org/maven2/commons-daemon/commons-daemon/1.3.4/

**Comment by 35C4n0r** [comment]
@pombredanne, below is the stacktrace for this, and it's occurring because of possibly malformed version range specification in the [POM](http://insecure.repo1.maven.org/maven2/org/apache/commons/commons-parent/57/commons-parent-57.pom).
Same issue for #197 [POM](http://insecure.repo1.maven.org/maven2/org/apache/commons/commons-parent/58/commons-parent-58.pom)

In both the cases the version range is specified as 
```
<activation>
<jdk>[9</jdk>
</activation>
```
Which is invalid and `pymaven` throws an error.

```
POM_URL = http://insecure.repo1.maven.org/maven2/commons-daemon/commons-daemon/1.3.4/commons-daemon-1.3.4.pom
POM_URL = http://insecure.repo1.maven.org/maven2/org/apache/commons/commons-parent/57/commons-parent-57.pom
ERROR Internal Server Error: /api/collect/
Traceback (most recent call last):
  File "/home/jay/purldb/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jay/purldb/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/jay/purldb/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/jay/purldb/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/jay/purldb/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/jay/purldb/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/jay/purldb/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/jay/purldb/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/jay/purldb/packagedb/api.py", line 547, in list
    errors = priority_router.process(purl)
  File "/home/jay/purldb/minecode/route.py", line 164, in process
    return endpoint(string, *args, **kwargs)
  File "/home/jay/purldb/minecode/visitors/maven.py", line 452, in process_request
    error = map_maven_binary_and_source(package_url)
  File "/home/jay/purldb/minecode/visitors/maven.py", line 374, in map_maven_binary_and_source
    package, emsg = map_maven_package(
  File "/home/jay/purldb/minecode/visitors/maven.py", line 306, in map_maven_package
    ancestor_pom_texts = get_ancestry(pom_text=pom_text, base_url=base_url)
  File "/home/jay/purldb/minecode/visitors/maven.py", line 195, in get_ancestry
    parent_pom_text = fetch_parent(pom_text=pom_text, base_url=base_url)
  File "/home/jay/purldb/minecode/visitors/maven.py", line 167, in fetch_parent
    pom = get_maven_pom(text=pom_text)
  File "/home/jay/purldb/venv/lib/python3.8/site-packages/packagedcode/maven.py", line 1003, in get_maven_pom
    pom.resolve(**extra_properties)
  File "/home/jay/purldb/venv/lib/python3.8/site-packages/packagedcode/maven.py", line 565, in resolve
    properties = dict(self.properties)
  File "/home/jay/purldb/venv/lib/python3.8/site-packages/pymaven/utils.py", line 50, in wrapper
    setattr(slf, name, func(slf, *args, **kwargs))
  File "/home/jay/purldb/venv/lib/python3.8/site-packages/pymaven/pom.py", line 465, in properties
    for profile in self._find_profiles():
  File "/home/jay/purldb/venv/lib/python3.8/site-packages/pymaven/pom.py", line 262, in _find_profiles
    vr = VersionRange.fromstring(jdk)
  File "/home/jay/purldb/venv/lib/python3.8/site-packages/pymaven/versioning.py", line 314, in fromstring
    return cls(spec)
  File "/home/jay/purldb/venv/lib/python3.8/site-packages/pymaven/versioning.py", line 226, in __init__
    raise VersionRangeParseError("Unbounded range: %s" % spec)
pymaven.errors.VersionRangeParseError: Unbounded range: [9
ERROR "GET /api/collect/?purl=pkg:maven/commons-daemon/commons-daemon@1.3.4 HTTP/1.1" 500 145
```

**Comment by 404-geek** [comment]
Hi @pombredanne is this issue open or solved.

I can work on it.
