### ISSUE TITLE
Increase version field length on Package

### ISSUE THREAD

**Issue by JonoYang** [nexB/purldb#25]
I'm running the visitor and mapper on npm packages and I get this error:
```
db_1          | 2023-02-07 01:30:52.710 UTC [35] ERROR:  value too long for type character varying(100)
db_1          | 2023-02-07 01:30:52.710 UTC [35] STATEMENT:  INSERT INTO "packagedb_package" ("history", "md5", "sha1", "sha256", "sha512", "extra_data", "filename", "primary_language", "description", "release_date", "homepage_url", "download_url", "size", "bug_tracking_url", "code_view_url", "vcs_url", "repository_homepage_url", "repository_download_url", "api_data_url", "copyright", "license_expression", "declared_license", "notice_text", "manifest_path", "contains_source_code", "datasource_id", "file_references", "uuid", "type", "namespace", "name", "version", "qualifiers", "subpath", "last_modified_date", "mining_level", "keywords", "root_path", "source_packages", "last_indexed_date", "index_error", "search_vector") VALUES ('', NULL, '4f93f3fc95c5f804c614c888a853bbe1a5aed6bc', NULL, 'e0389ae00348f541e2c2cead00140372b34d10095f7326c39d55694c04c78d0bfdc2e9ef5978968a78f763ad4ccadf99cbb45883f9007ef8f306fabe8eb79de5', '{}', 'rendition-21.4.7-fix-download-image-modal-alignment-when-no-compatible-device-types-00a8743f9a62aa7bf03fc63e4f9d84c1c1c3ba77.tgz', 'JavaScript', 'React components library', NULL, 'https://github.com/balena-io-modules/rendition#readme', 'https://registry.npmjs.org/rendition/-/rendition-21.4.7-fix-download-image-modal-alignment-when-no-compatible-device-types-00a8743f9a62aa7bf03fc63e4f9d84c1c1c3ba77.tgz', NULL, 'https://github.com/balena-io-modules/rendition/issues', NULL, 'git+https://github.com/balena-io-modules/rendition.git@00a8743f9a62aa7bf03fc63e4f9d84c1c1c3ba77', NULL, NULL, NULL, NULL, 'apache-2.0', '[''Apache-2.0'']', NULL, NULL, NULL, NULL, '[]', '05cfee42-58d5-46ea-b902-64fa3213af01'::uuid, 'npm', '', 'rendition', '21.4.7-fix-download-image-modal-alignment-when-no-compatible-device-types-00a8743f9a62aa7bf03fc63e4f9d84c1c1c3ba77', '', '', NULL, 0, '{}'::text[], NULL, '{}'::text[], NULL, NULL, NULL) RETURNING "packagedb_package"."id"
mapper_1      | ERROR:minecode.management.commands.run_map:Error: Failed to map while processing ResourceURI: <ResourceURI: https://registry.npmjs.org/rendition>
mapper_1      | While processing scanned_package: PackageData(type='npm', namespace=None, name='rendition', version='21.4.7-fix-download-image-modal-alignment-when-no-compatible-device-types-00a8743f9a62aa7bf03fc63e4f9d84c1c1c3ba77', datasource_id='npm_package_json')
mapper_1      | DataError DataError('value too long for type character varying(100)\n')
mapper_1      | Traceback (most recent call last):
mapper_1      |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
mapper_1      |     return self.cursor.execute(sql, params)
mapper_1      | psycopg2.errors.StringDataRightTruncation: value too long for type character varying(100)
mapper_1      | 
mapper_1      | 
mapper_1      | The above exception was the direct cause of the following exception:
mapper_1      | 
mapper_1      | Traceback (most recent call last):
mapper_1      |   File "/app/minecode/management/commands/run_map.py", line 288, in map_uri
mapper_1      |     created_package = Package.objects.create(**package_data)
mapper_1      |   File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
mapper_1      |     return getattr(self.get_queryset(), name)(*args, **kwargs)
mapper_1      |   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 671, in create
mapper_1      |     obj.save(force_insert=True, using=self.db)
mapper_1      |   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 812, in save
mapper_1      |     self.save_base(
mapper_1      |   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 863, in save_base
mapper_1      |     updated = self._save_table(
mapper_1      |   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1006, in _save_table
mapper_1      |     results = self._do_insert(
mapper_1      |   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1047, in _do_insert
mapper_1      |     return manager._insert(
mapper_1      |   File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
mapper_1      |     return getattr(self.get_queryset(), name)(*args, **kwargs)
mapper_1      |   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1790, in _insert
mapper_1      |     return query.get_compiler(using=using).execute_sql(returning_fields)
mapper_1      |   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1660, in execute_sql
mapper_1      |     cursor.execute(sql, params)
mapper_1      |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
mapper_1      |     return self._execute_with_wrappers(
mapper_1      |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
mapper_1      |     return executor(sql, params, many, context)
mapper_1      |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
mapper_1      |     return self.cursor.execute(sql, params)
mapper_1      |   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
mapper_1      |     raise dj_exc_value.with_traceback(traceback) from exc_value
mapper_1      |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
mapper_1      |     return self.cursor.execute(sql, params)
mapper_1      | django.db.utils.DataError: value too long for type character varying(100)
```

It looks like the version of this package (`21.4.7-fix-download-image-modal-alignment-when-no-compatible-device-types-00a8743f9a62aa7bf03fc63e4f9d84c1c1c3ba77`) is way too big.

**Comment by 35C4n0r** [comment]
@JonoYang, should we increase it to 255 ?
