### ISSUE TITLE
Error in merge_package

### ISSUE THREAD

**Issue by JonoYang** [nexB/purldb#26]
```
mapper_1      | INFO:minecode.management.commands.run_map:Mapping https://registry.npmjs.org/giphyapp
mapper_1      | ERROR:minecode.management.commands.run_map:Error: Failed to map while processing ResourceURI: <ResourceURI: https://registry.npmjs.org/giphyapp>
mapper_1      | While processing scanned_package: PackageData(type='npm', namespace=None, name='giphyapp', version='0.0.0', datasource_id='npm_package_json')
mapper_1      | KeyError KeyError('requirement')
mapper_1      | Traceback (most recent call last):
mapper_1      |   File "/app/minecode/management/commands/run_map.py", line 232, in map_uri
mapper_1      |     merge_packages(
mapper_1      |   File "/app/minecode/management/commands/run_map.py", line 442, in merge_packages
mapper_1      |     requirement=dependency['requirement'],
mapper_1      | KeyError: 'requirement'
```

**Comment by JonoYang** [comment]
This fix has been merged into main
