### ISSUE TITLE
`django.db.utils.DataError: value too long for type character varying(70)` when running run_map on npm packages

### ISSUE THREAD

**Issue by JonoYang** [nexB/purldb#28]
I got this error when mapping npm packages:
```
db_1          | 2023-02-08 19:11:01.991 UTC [34] ERROR:  value too long for type character varying(70)
db_1          | 2023-02-08 19:11:01.991 UTC [34] STATEMENT:  INSERT INTO "packagedb_party" ("package_id", "type", "role", "name", "email", "url") VALUES (7568090, 'person', 'contributor', 'Sucrase contains a modified fork of Babylon, which itself was forked from Acorn.', NULL, NULL) RETURNING "packagedb_party"."id"
mapper_1      | ERROR:minecode.management.commands.run_map:Error: Failed to map while processing ResourceURI: <ResourceURI: https://registry.npmjs.org/@mizchi%2fsucrase>
mapper_1      | While processing scanned_package: PackageData(type='npm', namespace='@mizchi', name='sucrase', version='4.0.0', datasource_id='npm_package_json')
mapper_1      | DataError DataError('value too long for type character varying(70)\n')
mapper_1      | Traceback (most recent call last):
mapper_1      |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
mapper_1      |     return self.cursor.execute(sql, params)
mapper_1      | psycopg2.errors.StringDataRightTruncation: value too long for type character varying(70)
mapper_1      | 
mapper_1      | 
mapper_1      | The above exception was the direct cause of the following exception:
mapper_1      | 
mapper_1      | Traceback (most recent call last):
mapper_1      |   File "/app/minecode/management/commands/run_map.py", line 292, in map_uri
mapper_1      |     Party.objects.create(
mapper_1      |   File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
mapper_1      |     return getattr(self.get_queryset(), name)(*args, **kwargs)
mapper_1      |   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 671, in create
mapper_1      |     obj.save(force_insert=True, using=self.db)
mapper_1      |   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 812, in save
mapper_1      |     self.save_base(
mapper_1      |   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 863, in save_base
mapper_1      |     updated = self._save_table(
mapper_1      |   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1006, in _save_table
mapper_1      |     results = self._do_insert(
mapper_1      |   File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1047, in _do_insert
mapper_1      |     return manager._insert(
mapper_1      |   File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
mapper_1      |     return getattr(self.get_queryset(), name)(*args, **kwargs)
mapper_1      |   File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1790, in _insert
mapper_1      |     return query.get_compiler(using=using).execute_sql(returning_fields)
mapper_1      |   File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1660, in execute_sql
mapper_1      |     cursor.execute(sql, params)
mapper_1      |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
mapper_1      |     return self._execute_with_wrappers(
mapper_1      |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
mapper_1      |     return executor(sql, params, many, context)
mapper_1      |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
mapper_1      |     return self.cursor.execute(sql, params)
mapper_1      |   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
mapper_1      |     raise dj_exc_value.with_traceback(traceback) from exc_value
mapper_1      |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
mapper_1      |     return self.cursor.execute(sql, params)
mapper_1      | django.db.utils.DataError: value too long for type character varying(70)
```
My initial guess is that there may be a package party parsing issue since the name of the party (`Sucrase contains a modified fork of Babylon, which itself was forked from Acorn.`) does not look like a name.

**Comment by JonoYang** [comment]
Another example of the error:
```
purldb-mapper-1   | ERROR:minecode.management.commands.run_map:Error: Failed to map while processing ResourceURI: <ResourceURI: https://registry.npmjs.org/rendition>
purldb-mapper-1   | While processing scanned_package: PackageData(type='npm', namespace=None, name='rendition', version='21.4.7-fix-download-image-modal-alignment-when-no-compatible-device-types-00a8743f9a62aa7b
f03fc63e4f9d84c1c1c3ba77', datasource_id='npm_package_json')
purldb-mapper-1   | DataError DataError('value too long for type character varying(100)\n')
purldb-mapper-1   | Traceback (most recent call last):
purldb-mapper-1   |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
purldb-mapper-1   |     return self.cursor.execute(sql, params)
purldb-mapper-1   | psycopg2.errors.StringDataRightTruncation: value too long for type character varying(100)
```
