### ISSUE TITLE
Possible error in ```setup.cfg``` of purldb and matchcode-toolkit.

### ISSUE THREAD

**Issue by 35C4n0r** [nexB/purldb#47]
While configuring the setup for matchcode-toolkit i encountered the following error:
```
Obtaining file:///home/jay/GSoC/purldb/matchcode-toolkit
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [37 lines of output]
      /tmp/pip-build-env-5pxve376/overlay/lib/python3.8/site-packages/setuptools/dist.py:561: UserWarning: The version specified ('9999.$Format:%h-%cs$') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
        warnings.warn(
      Traceback (most recent call last):
        File "/home/jay/GSoC/purldb/matchcode-toolkit/venv/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/jay/GSoC/purldb/matchcode-toolkit/venv/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/jay/GSoC/purldb/matchcode-toolkit/venv/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 181, in prepare_metadata_for_build_editable
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-5pxve376/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 451, in prepare_metadata_for_build_editable
          return self.prepare_metadata_for_build_wheel(
        File "/tmp/pip-build-env-5pxve376/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-5pxve376/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 6, in <module>
        File "/tmp/pip-build-env-5pxve376/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-5pxve376/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 159, in setup
          dist.parse_config_files()
        File "/home/jay/GSoC/purldb/matchcode-toolkit/venv/lib/python3.8/site-packages/_virtualenv.py", line 21, in parse_config_files
          result = old_parse_config_files(self, *args, **kwargs)
        File "/tmp/pip-build-env-5pxve376/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 881, in parse_config_files
          setupcfg.parse_configuration(
        File "/tmp/pip-build-env-5pxve376/overlay/lib/python3.8/site-packages/setuptools/config/setupcfg.py", line 174, in parse_configuration
          options.parse()
        File "/tmp/pip-build-env-5pxve376/overlay/lib/python3.8/site-packages/setuptools/config/setupcfg.py", line 504, in parse
          section_parser_method(section_options)
        File "/tmp/pip-build-env-5pxve376/overlay/lib/python3.8/site-packages/setuptools/config/setupcfg.py", line 479, in parse_section
          self[name] = value
        File "/tmp/pip-build-env-5pxve376/overlay/lib/python3.8/site-packages/setuptools/config/setupcfg.py", line 295, in __setitem__
          parsed = self.parsers.get(option_name, lambda x: x)(value)
        File "/tmp/pip-build-env-5pxve376/overlay/lib/python3.8/site-packages/setuptools/_vendor/packaging/specifiers.py", line 711, in __init__
          parsed.add(Specifier(specifier))
        File "/tmp/pip-build-env-5pxve376/overlay/lib/python3.8/site-packages/setuptools/_vendor/packaging/specifiers.py", line 245, in __init__
          raise InvalidSpecifier(f"Invalid specifier: '{spec}'")
      setuptools.extern.packaging.specifiers.InvalidSpecifier: Invalid specifier: '>=3.6.*'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

This error is because of  ```python_requires = >=3.6.*``` in the setup.cfg.
matchcode-toolkit:
https://github.com/nexB/purldb/blob/main/matchcode-toolkit/setup.cfg#L41
&&
purldb:
https://github.com/nexB/purldb/blob/main/setup.cfg#L61

[Fix]:
Changing the python version specifier to ```>=3.6``` fixes this issue.

@JonoYang @pombredanne

**Comment by JonoYang** [comment]
@35C4n0r Thanks for the report. I think we should update `python_requires = >=3.6.*` to `python_requires = >=3.7` as Python 3.6 is not supported anymore

**Comment by 35C4n0r** [comment]
@JonoYang PR updated.
